#!/usr/bin/env bash
#
# One command to run the EasyLife dashboard on http://localhost:3000.
#
# Starts Postgres, writes .env.local (generating secrets on first run),
# installs, builds, applies migrations, creates the first owner account,
# and serves the app. Safe to re-run: every step is idempotent, and it
# never overwrites an existing .env.local.
#
#   ./scripts/local-dev.sh
#
set -euo pipefail

cd "$(dirname "$0")/.."
ROOT="$(pwd)"
PORT="${PORT:-3000}"
COMPOSE_FILE="deploy/local/docker-compose.yml"

say()  { printf "\n\033[1;32m==>\033[0m %s\n" "$*"; }
warn() { printf "\n\033[1;33m!!\033[0m %s\n" "$*"; }
die()  { printf "\n\033[1;31mxx\033[0m %s\n" "$*" >&2; exit 1; }

# --- 1. Node ---------------------------------------------------------------
command -v node >/dev/null 2>&1 || die "Node isn't installed. Install Node 20+ (brew install node) and re-run."
NODE_MAJOR="$(node -p 'process.versions.node.split(".")[0]')"
[ "$NODE_MAJOR" -ge 20 ] || die "Node $NODE_MAJOR is too old - this app needs Node 20 or newer."
say "Node $(node -v)"

# --- 2. Postgres -----------------------------------------------------------
# An externally-supplied DATABASE_URL always wins, so anyone already running
# their own Postgres is never forced into Docker.
if [ -n "${DATABASE_URL:-}" ]; then
  say "Using the DATABASE_URL already set in your environment"
elif docker info >/dev/null 2>&1; then
  say "Starting Postgres via Docker"
  docker compose -f "$COMPOSE_FILE" up -d
  printf "    waiting for Postgres"
  for _ in $(seq 1 40); do
    if docker compose -f "$COMPOSE_FILE" exec -T postgres pg_isready -U easylife -d easylife_dev >/dev/null 2>&1; then
      printf " ready\n"; break
    fi
    printf "."; sleep 1
  done
  export DATABASE_URL="postgresql://easylife:easylife_local@127.0.0.1:5433/easylife_dev"
else
  die "Docker isn't running and DATABASE_URL isn't set.
    Either start Docker Desktop, or point this at your own Postgres:
      DATABASE_URL='postgresql://user:pass@127.0.0.1:5432/easylife_dev' ./scripts/local-dev.sh"
fi

# --- 3. .env.local ---------------------------------------------------------
# Never regenerated. Regenerating AUTH_SECRET would invalidate every existing
# session, and regenerating INTEGRATIONS_ENCRYPTION_KEY would make every saved
# credential permanently undecryptable.
if [ -f .env.local ]; then
  say "Keeping your existing .env.local"
else
  say "Creating .env.local with freshly generated secrets"
  cat > .env.local <<ENV
# Generated by scripts/local-dev.sh for LOCAL DEVELOPMENT ONLY.
# Never commit this file. Never reuse these values in production.
#
# NODE_ENV stays "production" even though this is your laptop: this script
# runs the same production build and the same app.js entry point that ships
# to cPanel, and Next refuses to prerender a production build under a
# "development" NODE_ENV. Chrome and Firefox both treat http://localhost as a
# trustworthy origin, so the Secure session cookie still works here.
NODE_ENV=production
APP_URL=http://localhost:${PORT}

# "database" unlocks Client Mode - the real dashboard. Without it every page
# silently falls back to the demo workspace.
AUTH_MODE=production
CRM_MODE=database
DEMO_MODE=false

DATABASE_URL=${DATABASE_URL}

AUTH_SECRET=$(openssl rand -hex 32)
INTEGRATIONS_ENCRYPTION_KEY=$(openssl rand -hex 32)
MIGRATION_TOKEN=$(openssl rand -hex 16)
SETUP_TOKEN=$(openssl rand -hex 16)

# Optional. Without a key the WhatsApp qualification bot still runs, using its
# built-in template replies instead of Gemini.
GEMINI_API_KEY=
ENV
fi

set -a; . ./.env.local; set +a
export PORT

# --- 4. Install and build --------------------------------------------------
if [ ! -d node_modules ]; then
  say "Installing dependencies (first run - this takes a minute)"
  # --include=dev is required, not optional: .env.local sets NODE_ENV=production
  # (the build needs it), and npm omits devDependencies under that NODE_ENV.
  # Without this the install silently succeeds and the build then fails on a
  # missing @tailwindcss/postcss.
  npm install --include=dev
else
  say "Dependencies already installed"
fi

say "Building"
npm run build

# --- 5. Serve --------------------------------------------------------------
say "Starting the server on port ${PORT}"
node app.js &
SERVER_PID=$!
# Always take the server down with this script, however it exits.
trap 'kill $SERVER_PID 2>/dev/null || true' EXIT INT TERM

printf "    waiting for the app"
for _ in $(seq 1 60); do
  if curl -fsS "http://127.0.0.1:${PORT}/api/health" >/dev/null 2>&1; then
    printf " up\n"; break
  fi
  printf "."; sleep 1
done

# --- 6. Migrations ---------------------------------------------------------
# Applied through the app's own runner - the same code path production uses,
# so a migration that works here works there.
say "Applying migrations"
curl -fsS -X POST -H "x-migration-token: ${MIGRATION_TOKEN}" \
  "http://127.0.0.1:${PORT}/api/admin/migrate" | sed 's/^/    /'
echo

# --- 7. First owner --------------------------------------------------------
# Returns an error once an owner exists; that is the expected steady state on
# every run after the first, so it is not treated as a failure.
LOGIN_EMAIL="${LOGIN_EMAIL:-owner@easylife.local}"
LOGIN_PASSWORD="${LOGIN_PASSWORD:-EasyLife!Local2026}"
SETUP_RESULT="$(curl -fsS -X POST -H "Content-Type: application/json" \
  -H "x-setup-token: ${SETUP_TOKEN}" \
  -d "{\"name\":\"Owner\",\"email\":\"${LOGIN_EMAIL}\",\"password\":\"${LOGIN_PASSWORD}\"}" \
  "http://127.0.0.1:${PORT}/api/setup" 2>/dev/null || true)"

case "$SETUP_RESULT" in
  *'"ok":true'*) say "Created the owner account" ;;
  *)             say "Owner account already exists - keeping it" ;;
esac

cat <<BANNER

  ┌──────────────────────────────────────────────────────┐
     EasyLife dashboard is running

     URL       http://localhost:${PORT}
     Email     ${LOGIN_EMAIL}
     Password  ${LOGIN_PASSWORD}

     Switch to "Client Mode" (top right) for the real
     dashboard. Demo Mode shows fabricated sample data.

     Ctrl-C to stop.
  └──────────────────────────────────────────────────────┘

BANNER

wait $SERVER_PID
